import { PlanState } from "./types";
import { calculateBudget, DESTINATION_DATA, ACCOMMODATION_DATA } from "./data";

export function buildPlanSummary(planState: PlanState): string {
  const budget = calculateBudget(
    planState.travelStyle || "balanced",
    planState.duration,
    planState.travelers,
    planState.accommodation || "hotel",
    planState.transport || "mixed",
    planState.destination || "dubai"
  );

  const destination = planState.destination
    ? DESTINATION_DATA[planState.destination].name
    : "Not selected";
  const accommodation = planState.accommodation
    ? ACCOMMODATION_DATA[planState.accommodation].name
    : "Not selected";

  const lines = [
    "KENZ — Dubai Trip Plan",
    "========================",
    "",
    `Destination: ${destination}`,
    `Travel style: ${planState.travelStyle || "Not selected"}`,
    `Duration: ${planState.duration} days`,
    `Travelers: ${planState.travelers}`,
    `Accommodation: ${accommodation}`,
    `Transport: ${planState.transport || "Not selected"}`,
    planState.startDate
      ? `Start month: ${planState.startDate.toLocaleString("en-US", { month: "long" })}`
      : null,
    "",
    "Budget breakdown",
    "----------------",
    ...Object.entries(budget.breakdown).map(
      ([category, amount]) => `${category}: $${amount.toLocaleString()}`
    ),
    "",
    `Estimated total: $${budget.total.toLocaleString()}`,
    `Per person: $${budget.perPerson.toLocaleString()}`,
    "",
  ];

  if (budget.recommendations.length > 0) {
    lines.push("Recommendations", "---------------");
    budget.recommendations.forEach((rec) => lines.push(`• ${rec}`));
    lines.push("");
  }

  lines.push("Generated by Kenz Pre-Planning Hub — gokenz.com");
  return lines.filter((line) => line !== null).join("\n");
}

export function downloadPlanAsText(planState: PlanState): void {
  const content = buildPlanSummary(planState);
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `kenz-trip-plan-${Date.now()}.txt`;
  link.click();
  URL.revokeObjectURL(url);
}

export function printPlanAsPdf(planState: PlanState): void {
  const content = buildPlanSummary(planState);
  const printWindow = window.open("", "_blank", "noopener,noreferrer,width=720,height=900");
  if (!printWindow) {
    downloadPlanAsText(planState);
    return;
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>Kenz Trip Plan</title>
        <style>
          body { font-family: Georgia, serif; padding: 40px; color: #141210; line-height: 1.6; }
          h1 { color: #ff6a00; font-size: 24px; margin-bottom: 8px; }
          pre { white-space: pre-wrap; font-family: inherit; font-size: 14px; }
        </style>
      </head>
      <body>
        <h1>Kenz Trip Plan</h1>
        <pre>${content.replace(/</g, "&lt;")}</pre>
      </body>
    </html>
  `);
  printWindow.document.close();
  printWindow.focus();
  printWindow.print();
}

export function encodePlanForUrl(planState: PlanState): string {
  const payload = {
    ...planState,
    startDate: planState.startDate ? planState.startDate.toISOString() : null,
  };
  return btoa(unescape(encodeURIComponent(JSON.stringify(payload))));
}

export function decodePlanFromUrl(encoded: string): PlanState | null {
  try {
    const parsed = JSON.parse(decodeURIComponent(escape(atob(encoded)))) as PlanState & {
      startDate: string | null;
    };
    return {
      ...parsed,
      startDate: parsed.startDate ? new Date(parsed.startDate) : null,
      completedMilestones: parsed.completedMilestones || [],
    };
  } catch {
    return null;
  }
}
